### ISSUE TITLE
Dependencies still appear to be off

### ISSUE THREAD

**Issue by EricWVGG** [LiveUI/S3#12]
building with 3.0.0-RC3.0.1

```
backgroundExecute(`
    code: 1,
    error: "error: the package PackageReference(identity: \"s3\", name: nil, path: \"https://github.com/LiveUI/S3.git\", isLocal: false) @ 3.0.0-alpha.1 contains revisioned dependencies:\n    PackageReference(identity: \"vaportesttools\", name: nil, path: \"https://github.com/LiveUI/VaporTestTools.git\", isLocal: false) @ master\n"
```

**Comment by Joebayld** [comment]
Having the same issue here..

**Comment by rafiki270** [comment]
Should be fixed in https://github.com/LiveUI/S3/pull/13, could you guys check?

**Comment by Joebayld** [comment]
I'm still having problems here. Do I need the VaporTestTools dependency? I'd rather just get rid of it for my use.

**Comment by rafiki270** [comment]
I see, we need it as it will be easiest way to test/mock S3 lib in your apps. I understand there is not much at the moment but there is quite lot of work coming into this ... but yeah, if there is a compatibility issue will fit that ASAP!

**Comment by Joebayld** [comment]
Got it. I'll try and sort out why this is being problematic and report back.

**Comment by rafiki270** [comment]
If you having issues I would assume problem will be somewhere downstream on the test tools dependencies

**Comment by rafiki270** [comment]
@mcdappdev really don't see what could be off :( ... any ideas?

**Comment by mcdappdev** [comment]
I'm not sure, unfortunately. Your package files seem to be ok but maybe it's something with `Package.resolved`?

**Comment by rausnitz** [comment]
I made a fork that only depends on Vapor and therefore avoids the aforementioned dependency problems. The fork only provides the S3 signer functionality, but if that's all you need, then it works: https://github.com/rausnitz/S3.

(I'm not sure why I had to specify the branch in Package.swift. When I tried doing `from: "3.0.0"` then my `vapor update` command would hang.)

**Comment by mcdappdev** [comment]
@rausnitz Awesome! I'll use yours. Thanks :)

**Comment by rafiki270** [comment]
guys, do you by any chance have any logs to share or does the process just freeze?

**Comment by lluuaapp** [comment]
I think this is an issue with the Swift Package Manager. I had this too, but updated the dependencies of the main project (all the latest version of the packages, some pinned to the latest version) and deleted Package.resolved. After that, run

`vapor build --verbose --clean`

and you will see the package that the package manager gets stuck resolving.

**Comment by EricWVGG** [comment]
This is working for me now with RC2.
